In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('iris_dataset.csv')
df.shape[0]

45

# PRECISION

In [3]:
TPs = df.query("retrieved == 'setosa' & gold_standard == 'setosa'").shape[0]
FPs = df.query("retrieved == 'setosa' & gold_standard != 'setosa'").shape[0]
print('Predicted as setosa and actual is also setosa= ',TPs,
      '\nPredicted as setosa but actual is not setosa= ',FPs)
Ps = TPs/(TPs+FPs)
print('Precision of setosa= ',round(Ps,2))

Predicted as setosa and actual is also setosa=  19 
Predicted as setosa but actual is not setosa=  0
Precision of setosa=  1.0


In [4]:
TPv = df.query("retrieved == 'versicolor' & gold_standard == 'versicolor'").shape[0]
FPv = df.query("retrieved == 'versicolor' & gold_standard != 'versicolor'").shape[0]
print('Predicted as versicolor and actual is also versicolor= ',TPv,
      '\nPredicted as versicolor but actual is not versicolor= ',FPv)
Pv = TPv/(TPv+FPv)
print('Precision of versicolor= ',round(Pv,2))

Predicted as versicolor and actual is also versicolor=  15 
Predicted as versicolor but actual is not versicolor=  0
Precision of versicolor=  1.0


In [5]:
TPvi = df.query("retrieved == 'virginica' & gold_standard == 'virginica'").shape[0]
FPvi = df.query("retrieved == 'virginica' & gold_standard != 'virginica'").shape[0]
print('Predicted as virginica and actual is also virginica= ',TPvi,
      '\nPredicted as virginica but actual is not virginica= ',FPvi)
Pvi = TPvi/(TPvi+FPvi)
print('Precision of virginica= ',round(Pvi,2))

Predicted as virginica and actual is also virginica=  7 
Predicted as virginica but actual is not virginica=  4
Precision of virginica=  0.64


# RECALL

In [6]:
FNs = df.query("retrieved != 'setosa' & gold_standard == 'setosa'").shape[0]
print('Not predicted as setosa but actual is setosa= ',FNs)
RecS = TPs/(TPs+FNs)
print('Recall of setosa= ',RecS)

Not predicted as setosa but actual is setosa=  0
Recall of setosa=  1.0


In [7]:
FNv = df.query("retrieved != 'versicolor' & gold_standard == 'versicolor'").shape[0]
print('Not predicted as versicolor but actual is versicolor= ',FNv)
RecV = TPv/(TPv+FNv)
print('Recall of versicolor= ',round(RecV,2))

Not predicted as versicolor but actual is versicolor=  4
Recall of versicolor=  0.79


In [8]:
FNvi = df.query("retrieved != 'virginica' & gold_standard == 'virginica'").shape[0]
print('Not predicted as virginica but actual is virginica= ',FNvi)
RecVi = TPvi/(TPvi+FNvi)
print('Recall of virginica= ',RecVi)

Not predicted as virginica but actual is virginica=  0
Recall of virginica=  1.0


# F-Score

In [9]:
Fs = 2*((RecS*Ps)/(Ps+RecS))
print('F-Score of setosa= ',Fs)

F-Score of setosa=  1.0


In [10]:
Fv = 2*((RecV*Pv)/(Pv+RecV))
print('F-Score of versicolor= ',round(Fv,2))

F-Score of versicolor=  0.88


In [11]:
Fvi = 2*((RecVi*Pvi)/(Pvi+RecVi))
print('F-Score of virginica= ',round(Fvi,2))

F-Score of virginica=  0.78


# PRECISION @ "10"

In [12]:
df2 = df[0:10]
df2

retrieved gold_standard
0      setosa        setosa
1      setosa        setosa
2      setosa        setosa
3  versicolor    versicolor
4      setosa        setosa
5  versicolor    versicolor
6   virginica    versicolor
7      setosa        setosa
8      setosa        setosa
9      setosa        setosa

In [13]:
TP2s = df2.query("retrieved == 'setosa' & gold_standard == 'setosa'").shape[0]
FP2s = df2.query("retrieved == 'setosa' & gold_standard != 'setosa'").shape[0]
TP2v = df2.query("retrieved == 'versicolor' & gold_standard == 'versicolor'").shape[0]
FP2v = df2.query("retrieved == 'versicolor' & gold_standard != 'versicolor'").shape[0]
TP2vi = df2.query("retrieved == 'virginica' & gold_standard == 'virginica'").shape[0]
FP2vi = df2.query("retrieved == 'virginica' & gold_standard != 'virginica'").shape[0]

P2s = TP2s/(TP2s+FP2s)
P2v = TP2v/(TP2v+FP2v)
P2vi = TP2vi/(TP2vi+FP2vi)
print('Precision of setosa @ "10"= ',P2s)
print('Precision of versicolor @ "10"= ',P2v)
print('Precision of virginica @ "10"= ',P2vi)

Precision of setosa @ "10"=  1.0
Precision of versicolor @ "10"=  1.0
Precision of virginica @ "10"=  0.0


# ACCURACY

In [18]:
TNs = df.query("retrieved != 'setosa' & gold_standard!= 'setosa'").shape[0]
ACCs = (TPs+TNs)/(TPs+TNs+FPs+FNs)
#print('Setosa accuracy= ', ACCs)
print("True Positive: ",TPs )
print("False Positive: ",FPs )
print("False Negative: ",FNs )
print("True Negative: ",TNs )

True Positive:  19
False Positive:  0
False Negative:  0
True Negative:  26


# MEAN AVERAGE PRECISION

In [12]:
MAP = (Ps+Pv+Pvi)/3
print('Mean Average Precision= ', round(MAP,2))

Mean Average Precision=  0.88


In [17]:
new_arr = df[1:5]
print(new_arr)

    retrieved gold_standard
1      setosa        setosa
2      setosa        setosa
3  versicolor    versicolor
4      setosa        setosa


In [24]:
new_arr2 = np.vstack((df, df2))

# new_arr = np.hstack((a, b))

# new_arr = numpy.stack((a, b))

# new_arr = numpy.hstack((a, b))

print(new_arr2)

[['setosa' 'setosa']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['versicolor' 'versicolor']
 ['virginica' 'versicolor']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['versicolor' 'versicolor']
 ['virginica' 'virginica']
 ['setosa' 'setosa']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['virginica' 'versicolor']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['versicolor' 'versicolor']
 ['versicolor' 'versicolor']
 ['setosa' 's

In [4]:
import numpy
a = numpy.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
